### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [jamestthompson3/nvim-remote-containers#13]
I cloned it inside the plugin folder but without success

**Comment by jamestthompson3** [comment]
Thanks for your interest in the plugin! I would recommend a plugin manager such as [packer](https://github.com/wbthomason/packer.nvim), [vim-plug](https://github.com/junegunn/vim-plug), or [dein](https://github.com/Shougo/dein.vim) since they make sure that the plugin is correctly installed in neovim's [pack path](https://neovim.io/doc/user/options.html#'packpath').
