### ISSUE TITLE
Module 'nvim _lsp/util' not found

### ISSUE THREAD

**Issue by chesedo** [jamestthompson3/nvim-remote-containers#2]
I have installed the plugin using packer with the following lines:

```lua
  use 'jamestthompson3/nvim-remote-containers'
```

However, on running `AttachToContainer` I get the following error:
```
E5108: Error executing lua .../pack/packer/start/nvim-remote-containers/lua/docker.lua:5: module 'nvim
_lsp/util' not found:
        no field package.preload['nvim_lsp/util']
...
```

So I changed the packer line to the following, but am getting the same error:
```lua
  use {
    'jamestthompson3/nvim-remote-containers',
    requires = {'RishabhRD/nvim-lsputils'},
  }
```

Any advice for where the missing module is located?

**Comment by jamestthompson3** [comment]
Thanks for your interest in this plugin! This was originally a quick weekend hack project that ended up being more or less copy-pasted from my config and it's been awhile since I've actually used it. However, now that more people are interested in it, I'm going through to fix things that are broken and trying to bring it up to reflect all of the new changes and improvements surrounding lua in Neovim. A first pass at fixing broken things and getting a smoother experience is taking place in this branch: https://github.com/jamestthompson3/nvim-remote-containers/tree/project-refresh

I hope to finish the basic fixes / improvements in a week.

**Comment by chesedo** [comment]
Nice!! I'll be happy to help out with testing.

Do you have a roadmap for the project? And a place for communication?

**Comment by jamestthompson3** [comment]
When I stopped working on it, I just dumped some ideas in the Projects tab in this repo. I think that's probably as good a place as any for figuring out what sort of features should take focus and planning things out. For comms, I think GH works pretty well :)

**Comment by rogermontilla01** [comment]
It looks great, please continue with it. thanks

**Comment by jamestthompson3** [comment]
Merged https://github.com/jamestthompson3/nvim-remote-containers/pull/3. I would now say that it's in a basic usable state. You can build and run an image as specified in a `devcontainer.json` file without any of the previously mentioned errors.
